### ISSUE TITLE
Cyclops installation fails in Windows

### ISSUE THREAD

**Issue by Adibvafa** [VectorInstitute/cyclops#485]
### Describe the bug
Installing Cyclops in a new conda environment on Windows is unsuccessful due to not finding any Python version that can satisfy all requirements.

### To Reproduce
Upon creation of a new conda environment, enter:
py -m pip install 'pycyclops[query,models]'

### Expected bug
![image](https://github.com/VectorInstitute/cyclops/assets/90617686/50bf71fa-c2b0-417d-ab3c-9e252c75bc3e)
![image](https://github.com/VectorInstitute/cyclops/assets/90617686/e6609aac-9296-404c-9835-f44b28853517)

### Additional Context
The bug does not occur when installing Cyclops on Kaggle Notebooks.

**Comment by armingh2000** [comment]
**Update:**
I just viewed the last commit before this issue and realized there were "models and query" dependencies in that version. Also, I realized this issue is probably fixed by now, so the solution is not needed. I am including it here anyway so that you can close the issue if it is fixed.

---

**Original answer:**
I think the issue is with the python version. 
I tried to reproduce the code and was successful in it. This is what I did:
```bash
conda create -n cyclops
pip install pycyclops[query,models]
```
Got the same error as yours.

When installing a conda environment, it defaults to the latest python version (right now, it is 3.12). However, as mentioned in the [requirements](https://github.com/VectorInstitute/cyclops/blob/4e00d6145d7c827d06ef44098a037928efc5e59a/pyproject.toml#L15), the version should be: **<3.11 and >=3.9**
To create a conda environment meeting the needs, I ran this code:

```bash
conda create -n cyclops python=3.10
pip install pycyclops[query,models]
```
I was able to install the dependencies w/o problems.
However, there was a warning:

![image](https://github.com/VectorInstitute/cyclops/assets/45814289/0170c7df-2296-4b03-9012-c38785c58d9f)

This means that there is no definition for the mentioned dependencies. As I went through the dependencies, I saw there are only definitions for these dependencies:
![image](https://github.com/VectorInstitute/cyclops/assets/45814289/9decc2e0-0316-4fc2-a910-421134adec1e)

**Comment by Adibvafa** [comment]
Yes, that should work! Also, I realized if you install Python==3.8 in the environment since the beginning, Cyclops can be installed without any bugs. Alternatively, a Windows user can set up the Windows Subsystem for Linux (WSL), install Cyclops there, and connect an IDE (VSC, PyCharm) to the Conda environment inside WSL for using Cyclops.
